# Generated by Django 2.2.16 on 2022-11-10 21:01

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221108_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[reviews.validators.validation_year], verbose_name='Год выпуска'),
        ),
    ]
