# Generated by Django 2.2.16 on 2022-11-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_t'),
        ('reviews', '0003_nata_001'),
    ]

    operations = [
    ]
