# Generated by Django 2.2.16 on 2022-11-11 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_20221111_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Значение меньше минимального.Значение должно быть от 1 до 10'), django.core.validators.MaxValueValidator(10, message='Значение больше максимального.Значение должно быть от 1 до 10')]),
        ),
    ]
