# Generated by Django 2.2.16 on 2022-11-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221107_2007'),
        ('reviews', '0004_auto_20221106_2256'),
    ]

    operations = [
    ]
